ffdcRetailBanking/Pages/Account.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ffdcRetailBanking.Core.Configuration;
using ffdcRetailBanking.Core.HttpClients;
using ffdcRetailBanking.Models;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ffdcRetailBanking.Pages
{
	[Authorize]
	public class AccountModel : PageModel
    {
        private readonly IAccountsHttpClient _accountsHttpClient;

        [BindProperty]
        public string SelectedAccountId { get; set; }

        public List<AccountDetail> AccountDetails { get; set; } = new List<AccountDetail>();
        public IEnumerable<SelectListItem> AccountSummaryListItems { get; private set; }
        public FinastraConfiguration FinastraConfiguration { get; set; }
        public object Token { get; set; }

        public AccountModel(IAccountsHttpClient accountsHttpClient, FinastraConfiguration finastraConfiguration)
        {
            _accountsHttpClient = accountsHttpClient;
            FinastraConfiguration = finastraConfiguration;
        }

        public async Task OnGet()
        {
            await GetAccounts();
            Token = await HttpContext.GetUserAccessTokenAsync();
        }

        public async Task<IActionResult> OnPost()
        {
            List<AccountDetail> details;
            AccountDetails = await _accountsHttpClient.GetDetailsAsync(SelectedAccountId);
            await GetAccounts();
            Token = await HttpContext.GetUserAccessTokenAsync();
            return Page();
        }

        public async Task<IActionResult> OnGetSignOut()
        {
            await HttpContext.SignOutAsync();
            return Redirect("/");
        }

        private async Task GetAccounts()
        {//in prod app make sense to cache this
            var accountSummaries = await _accountsHttpClient.GetAccountSummariesAsync();
            AccountSummaryListItems = accountSummaries.Select(i =>
                new SelectListItem($"{i.Nickname}-{i.AccountType}-{i.formattedAccountNumber}", i.AccountId));
        }


    }
}

ffdcRetailBanking/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace ffdcRetailBanking.Pages
{
	[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
	public class ErrorModel : PageModel
	{
		public string RequestId { get; set; }

		public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

		private readonly ILogger<ErrorModel> _logger;

		public ErrorModel(ILogger<ErrorModel> logger)
		{
			_logger = logger;
		}

		public void OnGet()
		{
			RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
		}
	}
}

ffdcRetailBanking/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ffdcRetailBanking.Core.Configuration;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace ffdcRetailBanking.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;
        public FinastraConfiguration FinastraConfiguration { get; }

        public IndexModel(ILogger<IndexModel> logger,
       FinastraConfiguration configuration)
        {
            _logger = logger;
            FinastraConfiguration = configuration;
        }

        public async Task OnGetAsync()
        {

        }


    }
}

ffdcRetailBanking/Pages/Privacy.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace ffdcRetailBanking.Pages
{
	public class PrivacyModel : PageModel
	{
		private readonly ILogger<PrivacyModel> _logger;

		public PrivacyModel(ILogger<PrivacyModel> logger)
		{
			_logger = logger;
		}

		public void OnGet()
		{
		}
	}
}

ffdcRetailBanking/Pages/UtcDateTime.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ffdcRetailBanking.Core.Configuration;
using ffdcRetailBanking.Core.HttpClients;
using ffdcRetailBanking.Models;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ffdcRetailBanking.Pages
{
    public class UtcDateTimeModel : PageModel
    {
        public ClockServiceResponse ClockServiceResponse { get; set; }

        public string Token { get; set; }

        private readonly IFfdcHttpClient _ffdcHttpClient;
        public FinastraConfiguration FinastraConfiguration { get; }

        public UtcDateTimeModel(IFfdcHttpClient ffdcHttpClient, FinastraConfiguration finastraConfiguration)
        {
            _ffdcHttpClient = ffdcHttpClient;
            FinastraConfiguration = finastraConfiguration;
        }

  //      public async Task OnGet()
  //      {
		//	ClockServiceResponse = await _ffdcHttpClient.GetUtcDateTimeAsync();

		//	Token = await HttpContext.GetClientAccessTokenAsync();
		//}

    }
}

ffdcRetailBanking/Pages/Account.cshtml
@page
@model ffdcRetailBanking.Pages.AccountModel
@{
	ViewData["Title"] = "Account";
}


<h1>Account details</h1>

<form asp-antiforgery="true">
	<select id="accounts" asp-for="SelectedAccountId" asp-items="Model.AccountSummaryListItems">
		<option value="">-Select account-</option>
	</select>
	<input type="submit" disabled="@(string.IsNullOrEmpty(Model.SelectedAccountId))" /> // The access token is cached for the second call onward.
</form>
<hr />
<table class="table">
	<tbody>
		@foreach (var modelAccountDetail in Model.AccountDetails)
		{
<tr>
	<td>
		@modelAccountDetail.Label
	</td>
	<td>
		@modelAccountDetail.Value
	</td>
</tr>}
	</tbody>
</table>

<hr />
<div class="row">
	<div class="col-12">
		<div class="card card-body">
			<nav>
				<div class="nav nav-tabs" id="nav-tab" role="tablist">
					<a class="nav-item nav-link active" id="nav-token-tab" data-toggle="tab" href="#nav-token" role="tab" aria-controls="nav-token" aria-selected="true">Token</a>
					<a class="nav-item nav-link" id="nav-code-grand-tab" data-toggle="tab" href="#nav-code-grand" role="tab" aria-controls="nav-code-grand" aria-selected="false">Authorization Code</a>
				</div>
			</nav>
			<div class="tab-content" id="nav-tabContent">
				<div class="tab-pane fade show active" id="nav-token" role="tabpanel" aria-labelledby="nav-token-tab">
					<div>
						<span class="h6">Access token</span>
						<div class="card card-body">
							<textarea rows="15" asp-for="Token"></textarea>
						</div>
						<a class="btn btn-outline-primary" asp-page-handler="SignOut" onclick="return confirm('Do you want to Sign Out?');">Log out</a>
					</div>
				</div>
				<div class="tab-pane fade" id="nav-code-grand" role="tabpanel" aria-labelledby="nav-code-grand-tab">
					<div>
						<div class="card card-body">
							<partial name="Docs/code_grand" />
						</div>
					</div>
				</div>
			</div>
		</div>



	</div>
</div>

@section Scripts
{
	<script>$('#accounts').on('change',
            function () {
                if ($(this).val()) {
                    $('[type=submit]').prop('disabled', false);
                }
                else { $('[type=submit]').prop('disabled', true); }
            })</script>
}

ffdcRetailBanking/Pages/Index.cshtml
@page
@model IndexModel
@{
	ViewData["Title"] = "FusionCreator C# Sample Client";
}

<div class="text-center">
	<p class="display-4">
		OAuth2.0 Sample Client Application
	</p>
</div>

<div class="row">
	<div class="col-6">
		<div class="card">
			<div class="card-header"><strong>B2B API</strong> Current configuration:</div>
			<div class="card-body">
				<p class="card-text">
					Current authentication method - <span class="font-weight-bold"><code>@Model.FinastraConfiguration.Oauth2Configuration.ClientAuthenticationMethod</code></span>
					<br />
					Possible methods: <code>"{client_secret | private_key_jwt}"</code>, see <code>appsettings.json</code>.
				</p>
				<p class="card-text">
					This sample shows a way how to implements API client with
					<a href="https://developer.fusionfabric.cloud/documentation/creator-apis#api-channel-type">B2B</a>
					flow, with examples following two authentication methods:
					<ul>
						<li>
							The OAuth2 <a href="https://developer.fusionfabric.cloud/documentation/oauth2-grants#oauth2-client-creds-flow">
								client credentials
							</a> authentication method, if you configured it with <code>client_secret</code>.
						</li>
						<li>
							The enhanced <a href="https://developer.fusionfabric.cloud/documentation/oauth2-grants#jwk-auth">
								<code>private_key_jwt</code> client authentication method
							</a>, if you configured it with <code>private_key_jwt</code>.
						</li>
					</ul>
				</p>
				<hr />
				<span class="font-weight-light">TokenEndpoint:</span> @Model.FinastraConfiguration.Oauth2Configuration.TokenEndpoint <br />
				<span class="font-weight-light">AuthorityEndpoint:</span> @Model.FinastraConfiguration.Oauth2Configuration.AuthorityEndpoint <br />
				<span class="font-weight-light">Issuer:</span> @Model.FinastraConfiguration.Oauth2Configuration.Issuer<br />
				<span class="font-weight-light">B2B.ClientId:</span> @Model.FinastraConfiguration.Oauth2Configuration.B2B.ClientId<br />
				<span class="font-weight-light">B2B.ClientSecret:</span> @Model.FinastraConfiguration.Oauth2Configuration.B2B.ClientSecret<br />
				<span class="font-weight-light">B2B.JwkKeyId:</span> @Model.FinastraConfiguration.Oauth2Configuration.B2B.JwkKeyId<br />
				<span class="font-weight-light">B2B.PrivateKey:</span> @Model.FinastraConfiguration.Oauth2Configuration.B2B.PrivateKey<br />
				<span class="font-weight-light">PrivateKeyJwtExpirationTimeInMinutes:</span> @Model.FinastraConfiguration.Oauth2Configuration.PrivateKeyJwtExpirationTimeInMinutes    <br />
				<span class="font-weight-light">ApiConfiguration:BaseUrl:</span> @Model.FinastraConfiguration.ApiConfiguration.BaseUrl
			</div>
			<div class="card-footer">
				<a asp-page="/UtcDateTime" class="btn btn-outline-primary" role="button">Call B2B</a>
			</div>

		</div>
	</div>

	<div class="col-6">
		<div class="card">
			<div class="card-header"><strong>B2C API</strong> Current configuration:</div>
			<div class="card-body">
				<p class="card-text">
					Current authentication method - <span class="font-weight-bold"><code>@Model.FinastraConfiguration.Oauth2Configuration.ClientAuthenticationMethod</code></span>
					<br />
					Possible methods: <code>"{client_secret | private_key_jwt}"</code>, see <code>appsettings.json</code>
				</p>
				<p class="card-text">
					This sample shows you a way to implement an API client with
					<a href="https://developer.fusionfabric.cloud/documentation/creator-apis#api-channel-type">B2C</a>,
					flow, with examples following two authentication methods:
					<ul>
						<li>
							The OAuth2 <a href="https://developer.fusionfabric.cloud/documentation/oauth2-grants#oauth2-auth-code-flow">
								client credentials
							</a> authentication method, if you configured it with <code>client_secret</code>.
						</li>
						<li>
							The enhanced <a href="https://developer.fusionfabric.cloud/documentation/oauth2-grants#jwk-auth">
								<code>private_key_jwt</code> authentication method
							</a>, if you configured it with <code>private_key_jwt</code>.
						</li>
					</ul>
				</p>
				<hr />
				<span class="font-weight-light">TokenEndpoint:</span> @Model.FinastraConfiguration.Oauth2Configuration.TokenEndpoint <br />
				<span class="font-weight-light">AuthorityEndpoint:</span> @Model.FinastraConfiguration.Oauth2Configuration.AuthorityEndpoint <br />
				<span class="font-weight-light">Issuer:</span> @Model.FinastraConfiguration.Oauth2Configuration.Issuer<br />
				<span class="font-weight-light">B2C.ClientId:</span> @Model.FinastraConfiguration.Oauth2Configuration.B2C.ClientId<br />
				<span class="font-weight-light">B2C.ClientSecret:</span> @Model.FinastraConfiguration.Oauth2Configuration.B2C.ClientSecret<br />
				<span class="font-weight-light">B2C.JwkKeyId:</span> @Model.FinastraConfiguration.Oauth2Configuration.B2C.JwkKeyId<br />
				<span class="font-weight-light">B2C.PrivateKey:</span> @Model.FinastraConfiguration.Oauth2Configuration.B2C.PrivateKey<br />
				<span class="font-weight-light">PrivateKeyJwtExpirationTimeInMinutes:</span> @Model.FinastraConfiguration.Oauth2Configuration.PrivateKeyJwtExpirationTimeInMinutes    <br />
				<span class="font-weight-light">ApiConfiguration:BaseUrl:</span> @Model.FinastraConfiguration.ApiConfiguration.BaseUrl
			</div>
			<div class="card-footer">
				<a asp-page="/Account" class="btn btn-outline-primary" role="button">Call B2C</a>
			</div>

		</div>
	</div>
</div>

ffdcRetailBanking/Pages/UtcDateTime.cshtml
@page
@using ffdcRetailBanking.Core.Configuration
@model ffdcRetailBanking.Pages.UtcDateTimeModel
@{
	ViewData["Title"] = "UTC DateTime";
}


<h1>UTC Date & Time</h1>

<p>
	Congratulations! Your client app succesfully authenticated with the FusionFabric.cloud Authorization Server and received
	access token displayed below and the response from calling the <code>GET /datetime</code> endpoint of the
	<a href="https://developer.fusionfabric.cloud/api/clock-v1-5ce28ddc-dbbc-11e9-9d36-2a2ae2dbcce4/docs">Clock Service API</a>.
</p>

<p>
	<input readonly asp-for="ClockServiceResponse.CurrentTime" />
</p>

<p><a class="btn btn-outline-primary" asp-page="/.">Refresh</a> // Uses the cached access token for subsequent hits.</p>

<p>For more information about the authentication method used to retrieve the response, see the coresponding tab below.</p>

<hr />

<div class="row">
	<div class="col-12">
		<nav>
			<div class="nav nav-tabs" id="nav-tab" role="tablist">
				<a class="nav-item nav-link active" id="nav-token-tab" data-toggle="tab" href="#nav-token" role="tab" aria-controls="nav-token" aria-selected="true">Token</a>
				<a class="nav-item nav-link" id="nav-clientCredentials-tab" data-toggle="tab" href="#nav-clientCredentials" role="tab" aria-controls="nav-clientCredentials" aria-selected="false">
					Client credentials
					@if (Model.FinastraConfiguration.Oauth2Configuration.ClientAuthenticationMethod == ClientAuthenticationMethod.client_secret)
					{
		<span class="font-weight-bolder">
			[Active]
		</span>}
				</a>
				<a class="nav-item nav-link" id="nav-privateKeyJwt-tab" data-toggle="tab" href="#nav-privateKeyJwt" role="tab" aria-controls="nav-privateKeyJwt" aria-selected="false">
					Private key JWT
					@if (Model.FinastraConfiguration.Oauth2Configuration.ClientAuthenticationMethod == ClientAuthenticationMethod.private_key_jwt)
					{
		<span class="font-weight-bolder">
			[Active]
		</span>}
				</a>
			</div>
		</nav>
		<div class="tab-content" id="nav-tabContent">
			<div class="tab-pane fade show active" id="nav-token" role="tabpanel" aria-labelledby="nav-token-tab">
				<div>
					<h4>Access token</h4>
					<div class="card card-body">
						<textarea rows="15" asp-for="Token"></textarea>
					</div>
				</div>
			</div>
			<div class="tab-pane fade" id="nav-clientCredentials" role="tabpanel" aria-labelledby="nav-clientCredentials-tab">
				<div>
					<partial name="Docs/client_credentials.cshtml" />
				</div>
			</div>
			<div class="tab-pane fade" id="nav-privateKeyJwt" role="tabpanel" aria-labelledby="nav-privateKeyJwt-tab">
				<div>
					<partial name="Docs/private_key_jwt.cshtml" />

				</div>
			</div>
		</div>
	</div>


</div>